### ISSUE TITLE
Calendar needs JDK annotations

### ISSUE THREAD

**Issue by mstaehely** [kelloggm/checker-framework#100]

**Comment by kelloggm** [comment]
I've looked into doing this. The Calendar class does all sorts of nasty things that make it difficult to annotate, but in particular it stores the length of several of its internal arrays as a single value and then expects its caller to know that value, because it allows access into the arrays without validation. Because of this (extremely dangerous) structure, I'm inclined not to annotate the class. What exactly do you need annotated in Calendar? Depending on how serious your need is, I can go ahead and do it anyway, although dealing with the classes' design will be problematic (and might make calling into the class difficult for clients that use the IC, because the restrictions on what can be passed to calendar will be strange).

**Comment by mstaehely** [comment]
What we would like annotated would be the return value of the .get(int field) method. If it's particularly difficult or problematic, I wouldn't worry too much about it.

**Comment by mernst** [comment]
Our policy is that a class is only added to the annotated JDK when all methods are annotated -- it's too confusing if some classes in the annotated JDK are only partially annotated.

That said, you could create and use a stub file in your own branch, that has only the annotation you really need.

**Comment by mstaehely** [comment]
Noted! That being the case, it seems like this might be an unnecessary issue.
