### ISSUE TITLE
Arrays of lowerbound/upperbound types not working?

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#109]
Consider the following code:
```java
import org.checkerframework.checker.index.qual.*;

class ArraysOfIFs {

    void fcn(@IndexFor("#2") int[] a, int[] b) {
	for (int i = 0; i < a.length; i++) {
	    @IndexFor("b") int indexForB = a[i];
	}
    }

    void test() {
	int[] a = {0,1,2,3};
	int[] b = new int[4];
	fcn(a,b);
    }
}
```

The first method (`fcn`) typechecks correctly. But the second (`test`) fails, because 0, 1, 2, and 3 are apparently not `@IndexFor("b")` - in fact, the whole array has type `@LowerBoundUnknown int @LowerBoundUnknown []` in the LBC, and the same with UB Unknown in the UBC. I'm not sure if this should work, or if the annotations I'm describing actually make sense. This example comes pretty much directly from plume-lib.

**Comment by smillst** [comment]
````
int[] b = new int[4];
int i = 0; 
````
The type of `i` is not refined to `@IndexFor("b")`.  It can be assigned to something with that type because `b` has type `@MinLen(4)` and `i` is known to be 0. 
````
int[] b = new int[4];
int[] a = {0,1,2,3};
````
Similarly, the types of 0, 1, 2, 3 are not refined to `@IndexFor("b")`, so `{0,1,2,3}` is not inferred to be `@IndexFor("b") int []`.

However, the Upper Bound Checker could be extend to handle the following:
````
int[] b = new int[4];
@IndexFor("b")  int[] a = {0,1,2,3};
````
Currently it gives the following error:
````
error: [assignment.type.incompatible] incompatible types in assignment.
        @IndexFor("b")	int[] a = {0,1,2,3};
                      	          ^
  found   : @UpperBoundUnknown int @UpperBoundUnknown []
  required: @LTLengthOf(value="b", offset={}) int @UpperBoundUnknown []
````

**Comment by kelloggm** [comment]
If every member of an array is known to have a particular type, should the whole array automatically get that type? For instance, if I have `int[] a = {0,1,2,3};`, should `a` have type `@NonNegative` in the LBC? Because all of its elements certainly do. I don't think this works, since the LBC gives it the type `@LowerBoundUnknown int @LowerBoundUnknown []`. This seems like something that ought to be implemented in general for arbitrary type systems...

**Comment by smillst** [comment]
The type of an array initializer depends on the assignment context.  
````
@NonNegative int[] a = {0,1,2,3}; // no error
````

This prevents false positive warnings.  For example:
````
int[] a = {0,1,2,3};  // no error
````

If `{0,1,2,3}` is given type `@NonNegative int []`, then the assignment would fail. `@NonNegative int @LowerBoundUnknown []` is not a sub type of `@LowerBoundUnknown int @LowerBoundUnknown []`.  Because if it were the following would be legal:
````
@NonNeg int [] x = ... ;
int[] y = x;
y[0] = -1;
````

**Comment by kelloggm** [comment]
That makes sense. So the code in the original example needs an `@IndexFor("b")` annotation on `a`, which means that `b` needs to be declared before `a`. I understand and will write a patch for this (and rewrite the appropriate annotations in plume-lib).

**Comment by kelloggm** [comment]
Thanks for explaining!

**Comment by kelloggm** [comment]
I've written a solution, which is on the branch constant-arrays. I'll make a PR once Suzanne's changes for polymorphic qualifiers are merged, since there's a dependency.
