### ISSUE TITLE
@MinLen(1) and type of .length/2

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#137]
Consider the following code:
```
import org.checkerframework.checker.index.qual.*;

public class newbug {
	public void m1(int @MinLen(1)[] a) {
		@IndexFor("a") int i = a.length/2; // checker warning	
	}
	//another test case
	public void m2(int [] a) {
		@IndexFor("a") int k;
		for(int i = a.length/2; i > 0; i--) {
			k = i; // checker warning
		}	
	}
}
```

Please note that the only case where `array.length/2` is not an `@IndexFor("array")` type is when the array is empty, so the above two cases should type check, but the index checker issues a warning.

```java
Index Checker Warning:
newbug.java:5: error: [assignment.type.incompatible] incompatible types in assignment.
		@IndexFor("a") int i = a.length/2; // checker warning	
		                               ^
  found   : @LTEqLengthOf("a") int
  required: @LTLengthOf(value="a", offset={}) int
newbug.java:11: error: [assignment.type.incompatible] incompatible types in assignment.
			k = i; // checker warning
			    ^
  found   : @LTEqLengthOf("a") int
  required: @LTLengthOf(value="a", offset={}) int
2 errors
```

**Comment by kelloggm** [comment]
Of these two cases, I think it's only reasonable for the Index Checker to correctly solve the first. Solving the second requires some complicated information to be available when `i > 0` is checked, because in order for that to refine a `LTEqLengthOf` to a `LTLengthOf`, we need to know that `i` is `a.length/2` when we're doing the comparison to zero. I don't think that's reasonable to expect. Does this second example appear in practical code often (or at all)?

The first part is an easy change that I'll make right away.
