### ISSUE TITLE
Interaction between @LessThanLength and @MinLen

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#14]
Consider this code:

```
public class ArrayLength2 {
    public static void main(String[] args) {
        int N = 8;
        int @MinLen(8) [] Grid = new int[N];
        @LessThanLength("Grid") int i = 0;
    }
}
```

This should type-check, but the final assignment fails.

This test case is checked into the repository as file `checker/tests/upperbound/ArrayLength2.java`.

**Comment by kelloggm** [comment]
This fails because we don't actually check MinLen when we're assigning variables; only when we actually make an array access. The reason for this is that in order to assign @LessThanLength("Grid") to i in the code above, we would need to check the MinLen of every array in scope. I don't know of a way to do that, and I believe that it's something I'm not supposed to do, either (although I might be wrong).

I don't see a way to fix this test case without checking every array in scope's MinLen on every assignment, which I view as undesirable.

**Comment by mernst** [comment]
It seems that this will make the checker more precise, with fewer false alarms.

Do you think it's undesirable because it will slow down the checker?  It's only necessary when an assignment rhs is a compile-time constant.  There generally won't be very many arrays with a `@MinLen` annotation, and these can be quickly found in the store.

**Comment by jsantino** [comment]
We did something similar to this in the old index checker; We put code in a method getminlens in the [IndexStore](https://github.com/gyhughes/checker-framework/blob/master/checker/src/org/checkerframework/checker/index/IndexStore.java) to get any minlen annotation and the receiver it applied to.
And then we called that method in the visitintegerliteral in the [IndexTransfer](https://github.com/gyhughes/checker-framework/blob/master/checker/src/org/checkerframework/checker/index/IndexTransfer.java) to apply the annotations to integer literals as they were introduced. since annotations applied to the integer itself it worked if the integer was used for in an assignment or a comparison
 ie.``if(int i < 8){ int k = Grid[i]; }``

**Comment by mernst** [comment]
In addition to taking advantage of `@MinLen` annotations, the checker should also take advantage of `@ArrayLen` annotations.  There are test cases in files `checker/tests/upperbound/ArrayLength2.java` and `checker/tests/upperbound/ArrayLength3.java`.
