### ISSUE TITLE
@ArrayLenRange annotation in Value Checker

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#150]
For integer variable values, the Value Checker can estimate sets of values or intervals.
For array lengths, the Value Checker only estimates sets of values.
It would be nice to extend the Value Checker to also estimate intervals for array lengths.

To do so, you would create a new type qualifier, `@ArrayLenRange`, that enhances `@ArrayLen` in the same way that `@IntRange` enhances `@IntVal`.  Probably no change to the Range.java class would be required -- just collecting information from program operations.

**Comment by kelloggm** [comment]
This would hopefully allow us to integrate the MinLen Checker into the Value Checker (where it probably should be). The MinLen Checker can be thought of as a range checker for array lengths that only tracks the lower bound of the range (the `from` variable in `Range.java`), so much of its logic could probably be recycled.

We would want `@ArrayLenRange(from = 0)` annotations to automatically be applied to arrays, since array lengths can't be negative.

Another issue is dealing with overflow: all Index Checker checkers explicitly assume no overflow. So some of the things the MinLen checker does might not be possible using an `@ArrayLenRange` annotation that does not ignore overflow. Perhaps we should have a "no overflow" mode for `Range`? This would be very useful for integrating the Lower Bound Checker into the Value Checker as well - its types are basically range types with only a lower bound, as well, that assume no overflow.

**Comment by JasonMrX** [comment]
@kelloggm, I was wondering what do you mean by "explicitly assume no overflow"? Could you please give an example?
I think how to refactor/redesign the `range` class to adapt to this situation greatly depend on the meaning of "no overflow". Does it mean:
- Assume that there is no use case that would cause overflow (unlikely the case, right?)
- If overflow, simply give up the analysis and return a full range, e.g., `@ArrayLenRange(from = 0)`
- Other thoughts?

**Comment by kelloggm** [comment]
The first case you mentioned: "Assume that there is no use case that would cause overflow"

You said this was unlikely, and I actually agree - but I strongly believe in separating concerns, and I would argue that a separate "overflow checker" (which I don't think exists in the Checker Framework, unfortunately) should be run to deal with overflow, and that the various components of the Index Checker should then be able to ignore overflow. Reasoning about array indices is already quite complex, and adding the need to reason about overflow, as well, makes the problem extremely difficult (because a lot of simple operations, like adding one to an index, _could_ cause overflow, so the checker would end up being much less precise).

**Comment by JasonMrX** [comment]
I see you point and agree. I will keep it in mind and think about it. At the same time, would you mind providing an example of how the MinLen Checker deal with the case of overflow (although we assume there is no overflow, but when it does happen, how the code handle it?), for example:
```java
void test() {
  int a = Integer.MAX_VALUE; // I am guessing here it is @MinLen(Integer.MAX_VALUE), right?
  int[] b = new int[a + 1]; // still @MinLen(Integer.MAX_VALUE)? or @MinLen(0)?
}
```

**Comment by kelloggm** [comment]
The MinLen Checker doesn't even consider the possibility. Since it internally uses longs, the resulting array would have type `@MinLen(Integer.MAX_VALUE + 1)`.

**Comment by smillst** [comment]
Actually, the minlen of `new int[a + 1]` is  computed using the `@ArrayLen`.  But there's a bug in the Value Checker. The type of `new int[a + 1]` should be `@BottomVal`, but it is  `@ArrayLen(Integer.MIN_VALUE)`.  Once that is fixed (which I'll do), the MinLen annotation should be `@MinLen(0)`.

**Comment by JasonMrX** [comment]
Ah! That's it. The `Range` class use `long` internally as well (modelling 64-bit integral range), so there won't be overflow handling in the `Range` library when only deal with `int`. The overflow handling is in fact in the value checker not the `Range` class -- that is, the `Range` class only provides APIs (`Range#intValue`, `Range#shortValue`), so when the checker finds out that the underlying type is not `long` (but `int`, `short` or `byte`), it calls the APIs and convert the range with the consideration of overflow. For example:
```java
void test() {
  int a = Integer.MAX_VALUE;
  int b = a + 1; // b has @IntVal({Integer.MIN_VALUE})
  long c = a + 1; // c has @IntVal({Integer.MAX_VALUE + 1})
}
```
It means that, in the calculation in the `Range` class, there is no overflow considered -- the range of `a + 1` is `[Integer,MAX_VALUE + 1, Integer.MAX_VALUE + 1]`. After that, it is the value checker that determine if we need to convert this range to a 32/16/8-bit version according to the underlying type (int/short/byte) by explicitly calling `Range#intValue`/`Range#shortValue`/`Range#byteValue`. 

What I am trying to say is, I think it is safe (no overflow consider at all) to use the `Range` library if the values you are targeting is within 32-bit integers.

**Comment by JasonMrX** [comment]
I found it really hard for me to explain this clearly.. but here are some facts about the `Range` class:
1. Overflow is only considered for 64-bit integers
2. Overflow is not going to happen if the values are within 32-bit integers
3. Overflow handling for 32-bit (or low) integers is happening outside of the `Range` class by calling the APIs provided: `Range#intValue`/`Range#shortValue`/`Range#byteValue` depending on the underlying type.

**Comment by kelloggm** [comment]
Your comment makes sense. Based on that, it sounds like `Range` shouldn't need to be changed - just the way that it's used by the Value Checker. Right now, the Value Checker calls `Range#intValue` whenever the value is an integer (like an array's length), but a version that ignores overflow could just not make that call.

**Comment by JasonMrX** [comment]
Yes, exactly my point!

**Comment by kelloggm** [comment]
Excellent. That sounds like it will be much simpler than needing to rebuild the `Range` library to ignore overflow - we should only need to create an option in the Value Checker to not do the conversion.
