### ISSUE TITLE
Random Array Access 

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#27]
```
void test() {
	Random rand = new Random();
	int[] a = new int[8];
	@NonNegative @LessThanLength("a") int deref = (int)(Math.random()*a.length);
	@NonNegative @LessThanLength("a") int deref2 = (int)(rand.nextDouble()*a.length);
	@NonNegative @LessThanLength("a") int deref3 = rand.nextInt(a.length);
}
```

These test cases result in the lowerbound and upperbound checker reporting the type of deref, deref2, and deref3 as LowerBoundUnknown and UpperBoundUnknown.

**Comment by kelloggm** [comment]
All of these are now solved with caf9eedba85bb95a0f0d8c40e563a3d2b86e77b8 and 2b7a78746fe8b9c1505b55af40e9fd6aea79b7e2. The only exception is the last one: it needs to be fixed with a JDK annotation. Joe has already done that annotation for the LBC, but the UBC one doesn't exist yet, so the test I wrote for the UBC (RandomTest.java, here: 540696de533a09b7cb8dda046beb4712a077ea1e) is set to skip. I'm closing this issue and will open a new one just for that.
