### ISSUE TITLE
Need annotation on JDK for UBC Random.nextInt

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#46]
There's a test for this here: 540696de533a09b7cb8dda046beb4712a077ea1e

**Comment by jsantino** [comment]
These cannot be handled in the JDK:

The pattern in the first three is  
X * LTLengthOf("a")

Which i would think would need to be handled with a combination of the value checker and upperbound checker in the UpperBoundTransfer

ie. @LTEqLengthOf("a") * (value between 0 and 1 exclusive) = @LTLength("a")


For the last case: `@LTLengthOf("a") int deref3 = rand.nextInt(a.length);`
i don't believe this can be done in the jdk because it would need to check the annotation on the parameter to apply it to the return.
And in the annotations you can only add requirements on the input/specify output ie i could say it always must be @LTLengthOf("array") and return the same but that is not true.

For this my thought is that it would have to be an explicit rule added in UBC that says if this Random.NextInt(x) and x has type @LTLengthOf("array") then apply that to the return.

**Comment by kelloggm** [comment]
You're right; I didn't think this through.

**Comment by jsantino** [comment]
Based on mernst's reply to #56 it may be possible to handle the last one with annotations using a [Polymorphic qualifier](https://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#qualifier-polymorphism)

**Comment by jsantino** [comment]
Nevermind; it cant be done with polymorphics, since the result is @LTLength and the argument is LTEqLength; Polymorphics can only apply the same type to each side.
