### ISSUE TITLE
JDK annotation for endsWith

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#56]
The JDK should be annotated so that if endsWith returns true, then the receiver has `@MinLen` at least that of the argument.

See a test case in `checker-framework/checker/tests/minlen/EndsWith.java`.

**Comment by jsantino** [comment]
how would that work? i imagine you could use the ensuresqualifierif to say it has an @MinLen if the method returns true; but how would it say that the @MinLen assigned is the same as the arguments one?

**Comment by mernst** [comment]
Please see section [Qualifier polymorphism](https://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#qualifier-polymorphism) in the manual.  Feel free to ask if that is not clear.

**Comment by mernst** [comment]
(In addition to `endsWith`, this needs to handle `startsWith`, of course.)

**Comment by mernst** [comment]
This is blocked on #73

**Comment by kelloggm** [comment]
Also blocked on #80

**Comment by panacekcz** [comment]
`@EnsuresQualifierIf` with a polymorphic qualifier cannot be used to express this property, because [`@MinLen`](https://checkerframework.org/api/org/checkerframework/common/value/qual/MinLen.html) is now in the value hierarchy, and the polymorphic qualifier [`@PolyValue`](https://checkerframework.org/api/org/checkerframework/common/value/qual/PolyValue.html) would mean that the receiver string value must be the same as the argument.
To get this functionality now, I am implementing it by special-casing the `startsWith` and `endsWith` methods in `ValueTransfer` (panacekcz#6).

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/61ca84e7b579d5b3e491b52b4b00ae57200f9ef9
