### ISSUE TITLE
Integer overflow can cause inaccurate types

### ISSUE THREAD

**Issue by jashug** [kelloggm/checker-framework#84]
The following code causes an integer overflow, making the index checker think that x2 is positive when it is interpreted as a large negative value.

The following code issues no warnings when checked with the index checker, and causes an ArrayIndexOutOfBoundsException on line 9 `a[x2] = 42;` when run. I expected the index checker to warn about this invalid array access, since 

> The Index Checker prevents IndexOutOfBoundsExceptions that result from an index expression that might be negative or might be equal to or larger than the sequence’s length

according to the manual. The word overflow is not mentioned in the manual to qualify this statement.

```
import org.checkerframework.checker.index.qual.*;

public class IndexOverflow {
    public static void main(String[] args) {
        @Positive int x = 1073741825; // 2 ^ 30 + 1
        @Positive int x2 = x + x; // 2 ^ 31 + 2 == - 2 ^ 31 + 2
        int[] a = new int[0];
        if (x2 < a.length) {
            a[x2] = 42;
        }
    }
}
```

Commands are `javac -processor index IndexOverflow.java` to compile and check, and `java IndexOverflow` to run. The output of `javac -processor index -version -verbose -AprintErrorStack -AprintAllQualifiers IndexOverflow.java` is attached below.

[IndexOverflow.txt](https://github.com/kelloggm/checker-framework/files/741388/IndexOverflow.txt)

**Comment by mernst** [comment]
Thanks for noticing and reporting this issue, Jasper.  You are correct.

By design, the Index Checker ignores overflow.
I will add this to the documentation.

There should really be a separate Overflow Checker that could be used in conjunction with any other checker that manipulates numbers.  That would be better than having multiple different checkers each implement their own overflow checking.

I'll update the manual and close this issue.  Thanks again!
