### ISSUE TITLE
MinLen Bug

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#95]
Consider the code:
```
import org.checkerframework.checker.index.qual.*;

public class MinLenBug {
	public static void m1(@Positive int i) {
		int @MinLen(2)[] a = new int[i + 1];	//index checker warning
	}

}
```

The parameter i being passed in is positive, therefore, array 'a' should have atleast a length of 2 however the index checker issues a warning.

Checker Warning:
MinLenBug.java:5: error: [assignment.type.incompatible] incompatible types in assignment.
		int @MinLen(2)[] a = new int[i + 1];
		                     ^
  found   : @MinLen(0) int @MinLen(0) []
  required: @MinLen(0) int @MinLen(2) []
1 error

**Comment by kelloggm** [comment]
I don't think it's reasonable to expect that the created array is @MinLen(2). That would require the checker to keep track of the range of possible values each expression can take on, which is beyond its scope. However, it would be nice if an array created with a positive number were @MinLen(1); but doing so would require the LBC to run before the MinLen checker, which I don't think is possible, since the LBC depends on the MinLen checker.

**Comment by kelloggm** [comment]
Duplicate with #66.
